development:
  adapter: postgresql
  encoding: unicode
  database: foodsafety_development
  pool: 5
  timeout: 5000
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: foodsafety_test
  pool: 5
  timeout: 5000
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: foodsafety_production
  pool: 5
  timeout: 5000
  password:

cucumber:
  <<: *test
